// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debt.proto

package ledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Debt struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Debt) Reset()         { *m = Debt{} }
func (m *Debt) String() string { return proto.CompactTextString(m) }
func (*Debt) ProtoMessage()    {}
func (*Debt) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa85ec7ea610725, []int{0}
}

func (m *Debt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Debt.Unmarshal(m, b)
}
func (m *Debt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Debt.Marshal(b, m, deterministic)
}
func (m *Debt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Debt.Merge(m, src)
}
func (m *Debt) XXX_Size() int {
	return xxx_messageInfo_Debt.Size(m)
}
func (m *Debt) XXX_DiscardUnknown() {
	xxx_messageInfo_Debt.DiscardUnknown(m)
}

var xxx_messageInfo_Debt proto.InternalMessageInfo

func (m *Debt) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Debt) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*Debt)(nil), "ledger.Debt")
}

func init() { proto.RegisterFile("debt.proto", fileDescriptor_2fa85ec7ea610725) }

var fileDescriptor_2fa85ec7ea610725 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x4d, 0x2a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x49, 0x4d, 0x49, 0x4f, 0x2d, 0x52, 0x32,
	0xe0, 0x62, 0x71, 0x49, 0x4d, 0x2a, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x52, 0x8b, 0x93,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x01, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0x25, 0xc1, 0xe6, 0x4e, 0x00, 0x00, 0x00,
}
